version: '3.8'

services:
  minio-perm:
    image: minio/minio
    container_name: minio-perm
    ports:
      - "9000:9000"  # This one for the UI to manage the buckets inside the storage
      - "9001:9001"  # For administration and health checking if I want to
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minioperm-data:/data
    command: server /data --console-address ":9001" # this is needed to run the container and tell him it will store the objects in /data and run 9001 for cofigure the startup scripts.
    networks:
      - ObjectStore

  minio-tmp:                   
    image: minio/minio
    container_name: minio-tmp
    ports:
      - "9002:9000"  
      - "9003:9001"  
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - miniotmp-data:/data
    command: server /data --console-address ":9001"
    networks:
      - ObjectStore
  
  minio-perm-replica:                   
    image: minio/minio
    container_name: minio-perm-replica
    ports:
      - "9004:9000"  
      - "9005:9001"  
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio-perm-replica-data:/data
    command: server /data --console-address ":9001"
    networks:
      - ObjectStore





volumes:
  minioperm-data:    # for temp
    driver: local  # the default 
  miniotmp-data:    # for perm
  minio-perm-replica-data:

networks:
  ObjectStore:
    name: ObjectStore
    external: false
