version: '3.8'

services:
  server1:
    build: .
    container_name: server-1
    ports:
      - "8000:8000"  
    environment:
      - PORT=8000  # Set the PORT environment variable
      - server=server_1
    volumes:
      - "D:/Mini posting website/Mini posting website/MainServer:/app"

    networks:
      - LoadBalancerNetwork
      - event-streaming
      - database-network



  server2:
    build: . 
    container_name: server-2
    ports:
      - "8001:8000" 
    environment:
      - PORT=8000  # Set the PORT environment variable
      - server=server_2
    volumes:
      - "D:/Mini posting website/Mini posting website/MainServer:/app"
    networks:
      - LoadBalancerNetwork
      - event-streaming
      - database-network

networks:
  LoadBalancerNetwork:
    name: loadbalancing
    driver: bridge
    external: false
  event-streaming:
    name: event-streaming
    driver: bridge
    external: false
  database-network:
    name: database-network
    external: false

  
